feature(VILLB-300-301): create abstract file storage service and s3fileStorage service.
BrewInteractive/nestjs-storage-module pull request #1
Opened 2024-07-22 08:00 UTC by katafalque

2024-07-22 10:09 UTC, erailea commented on src/providers/aws/s3-file-storage.config.ts
> +    s3ServiceBucket: string;
it is already s3config so no need for redundancy.

accessKey
secretKey
region
bucket

2024-07-22 12:40 UTC, erailea reviewed
lint and format required.

2024-07-22 12:45 UTC, erailea requested changes

2024-07-22 12:45 UTC, erailea commented on src/file-storage.module.ts
> +                    accessKeyId: '',
should get from config

2024-07-22 12:45 UTC, erailea commented on src/file-storage.module.ts
> +    imports: [],
should import ConfigModule with storage config

2024-07-23 08:52 UTC, ismetkizgin requested changes

2024-07-23 08:52 UTC, ismetkizgin commented on src/file-storage.service.ts
> +  abstract store(file: Buffer, path: string, config: any);
Why don't we say upload instead of store?

2024-07-23 08:52 UTC, ismetkizgin commented on src/file-storage.service.ts
> +  abstract store(file: Buffer, path: string, config: any);
Return type must be specified.

2024-07-23 08:52 UTC, ismetkizgin commented on src/file-storage.service.ts
> +  abstract delete(path: string);
Return type must be specified.

2024-07-23 09:41 UTC, erailea commented on src/file-storage.module.ts
> +        console.log(fileStorageType);
remove console log

2024-07-23 09:41 UTC, erailea commented on src/file-storage.module.ts
> +            throw new Error('Wrong Storage Type');
add test for invalid storage type

2024-07-23 10:42 UTC, ismetkizgin commented on src/file-storage.module.spec.ts
> +    process.env.STORAGE_SERVICE = FileStorageType.S3;
Env should not be mocked directly, it may affect the tests. ConfigService should be mocked directly.

2024-07-25 13:47 UTC, erailea requested changes
add main to package.json

2024-07-25 13:48 UTC, erailea requested changes
remove private true from package.json

2024-07-25 13:48 UTC, erailea requested changes
add readme

2024-07-25 13:49 UTC, erailea requested changes
add release library and script

2024-07-25 13:51 UTC, erailea requested changes
move @nestjs libraries to version 9 to keep a standart between @brewww libraries

2024-07-25 13:53 UTC, erailea requested changes
remove unused libraries like automapper

2024-07-25 13:54 UTC, erailea requested changes
add another store method for upload with base64.

2024-07-25 13:56 UTC, mehmetsagdur requested changes
Project name must start with @brewww/ for package.json

2024-07-25 13:58 UTC, erailea commented
remove e2e tests and configs

2024-07-30 06:55 UTC, merged